### ISSUE TITLE
Story Page

### ISSUE THREAD

**Issue by chalucks** [kaogeek/spanboon#162]
- [x] ให้เปลี่ยนเป็น Preload
- [x] โหลดข้อมูลไม่ขึ้น
- [x] กด Link แล้วไม่ไป Tab ใหม่
> - [ ] เก็บ Format (Desktop + Mobile) ให้เรียบร้อย
> <img width="250" src="https://user-images.githubusercontent.com/76645048/116023165-d16e8e00-a675-11eb-8d41-53fab7f1c371.png">

**Comment by junsudas** [comment]
All Clear
