### ISSUE TITLE
หน้า Search - Post มี Hashtag แต่ค้นหาจาก Hashtag แล้วโพสต์ไม่ขึ้น

### ISSUE THREAD

**Issue by chalucks** [kaogeek/spanboon#169]
<img src="https://user-images.githubusercontent.com/76645048/116344036-c6e7fc00-a80f-11eb-8f00-710341b6904c.png" width="800">
<img src="https://user-images.githubusercontent.com/76645048/116343543-cf8c0280-a80e-11eb-8080-d473a2b24ac1.png" width="800">

**Comment by p-nattawadee** [comment]
@chalucks review code
