### ISSUE TITLE
กล่อง Post

### ISSUE THREAD

**Issue by chalucks** [kaogeek/spanboon#198]
- [x] Copy ข้อความจากที่อื่นมาวาง ข้อความขึ้นซ้ำกัน [1]
- [ ] กด "โพสต์แล้ว" ให้ disabled ปุ่มและใส่ loading [2]

![Screen Shot 2564-06-04 at 16 19 44](https://user-images.githubusercontent.com/76645048/120779557-5db38100-c551-11eb-93c4-e1649b2243d3.png)

**Comment by p-nattawadee** [comment]
@chalucks  review code
