### ISSUE TITLE
หน้า Search

### ISSUE THREAD

**Issue by chalucks** [kaogeek/spanboon#204]
> - [x] กดบอกต่อไม่ได้
> 
> https://user-images.githubusercontent.com/76645048/122037360-b232e800-cdfe-11eb-8e04-c614e5614b58.mp4
> 
> https://user-images.githubusercontent.com/76645048/122037395-bc54e680-cdfe-11eb-8b79-9f3ae5c41439.mp4

> - [x] คอมเม้นไม่ได้
> 
> https://user-images.githubusercontent.com/76645048/122037543-ddb5d280-cdfe-11eb-9872-8dfbb494c6af.mp4

> - [ ] ค้นหาแล้วไม่เกิด action
> 
> https://user-images.githubusercontent.com/76645048/122037847-31282080-cdff-11eb-9216-682458497d17.mp4

**Comment by junsudas** [comment]
[BUG] ค้นหาแล้วไม่เกิด action: เทสแล้วเกิดจากการค้นแล้วส่ง offset ไปผิด
