### ISSUE TITLE
หน้า UserTimeline

### ISSUE THREAD

**Issue by chalucks** [kaogeek/spanboon#205]
- [x] โพสต์ไม่ได้

https://user-images.githubusercontent.com/76645048/122038149-8106e780-cdff-11eb-8207-0105b9ef514f.mp4

- [ ] โพสต์วีดีโอไม่ได้

https://user-images.githubusercontent.com/76645048/122038319-adbaff00-cdff-11eb-9b6f-a70ba40ef30f.mp4

- [x] โพสต์รูปไม่ได้

**Comment by junsudas** [comment]
ระบบยังไม่รองรับการโพสต์วีดีโอ ดังนั้นจึงขอปิดเคสนี้
