### ISSUE TITLE
[API] - หน้า Home

### ISSUE THREAD

**Issue by chalucks** [kaogeek/spanboon#225]
- [x] Objective ที่ไม่มีโพสต์ ไม่ต้องแนะนำให้ติดตามในหน้าแรก
<img src="https://user-images.githubusercontent.com/76645048/125717067-db8c41ad-33f9-4344-904f-1a458a49c9d3.jpg" width="300">

- [x] Page ที่ไม่มีโพสต์ ไม่ต้องแนะนำให้ติดตามในหน้าแรก
<img src="https://user-images.githubusercontent.com/76645048/125717205-957e1fe6-0cc6-4c7a-b0ee-8332cbc0ca15.jpg" width="300">

**Comment by junsudas** [comment]
Page ที่ไม่มีโพสต์ ไม่ต้องแนะนำให้ติดตามในหน้าแรก -- ปกติเป็นแบบนั้นอยู่แล้ว
