### ISSUE TITLE
[UI] - Action Like

### ISSUE THREAD

**Issue by chalucks** [kaogeek/spanboon#240]
- กด Like แล้วไม่แสดงสีว่ากด Like อยู่

- [ ] หน้า Search
![Screen Shot 2564-07-27 at 15 53 13](https://user-images.githubusercontent.com/76645048/127126443-7a227311-2cb6-49bb-a8a7-898739ec9a32.png)

- [ ] หน้า Post
![Screen Shot 2564-07-27 at 15 53 19](https://user-images.githubusercontent.com/76645048/127126463-d2dece39-83ff-454e-83e8-ef867029aacb.png)

**Comment by Americaso** [comment]
ฝั่ง API ไม่ได้ ส่ง isLike มาให้ครับ 
api/main/content/search

**Comment by chalucks** [comment]
> ฝั่ง API ไม่ได้ ส่ง isLike มาให้ครับ
> api/main/content/search

@junsudas

**Comment by junsudas** [comment]
@Americaso ทำ isLike ส่งให้แล้ว มี 
- isLike สำหรับ ตัวเองเป็นคน like 
- likeAsPage สำหรับ page เป็นคน like
- isComment เมื่อมี comment

หมายเหตุ: ถ้าไม่มี like อาจเป็น false หรือ undefined
