### ISSUE TITLE
[UI] - หน้า Emergency Event

### ISSUE THREAD

**Issue by chalucks** [kaogeek/spanboon#264]
- ## รูปไม่ได้สัดส่วน
<img width="1406" alt="Screen Shot 2564-08-11 at 17 57 53" src="https://user-images.githubusercontent.com/76645048/129020829-0e84d8ea-2fb8-44ab-98f2-2ca18f2308bb.png">

- ## ย่อจอเล็กแล้ว UI พัง
<img width="1397" alt="Screen Shot 2564-08-11 at 17 23 44" src="https://user-images.githubusercontent.com/76645048/129022503-e16e8b72-cc3f-479a-98c7-7ee037990db9.png">

**Comment by Americaso** [comment]
ข้อ รูปไม่ได้สัดส่วน
ยังไม่พบจุดที่เกิด ปัญหา **
