### ISSUE TITLE
[UI] - หน้า Home (2)

### ISSUE THREAD

**Issue by chalucks** [kaogeek/spanboon#268]
- ## โพสต์ใน section ล่างสุด แสดงผลตัว popup เวลาชี้ที่ชื่อเพจผิด (ชี้ชื่อเพจ แต่ขึ้นชื่อ user ผู้โพสต์)
<img width="588" alt="Screen Shot 2564-08-13 at 07 15 35" src="https://user-images.githubusercontent.com/76645048/129291698-9c5c3ec9-8295-4148-bce4-f90a10ef25f3.png">

- ## สีของ hashtag ใน Dialog ตอนคลิกดูโพสต์ แสดงผลผิด (สีของ hashtag ไม่ใช่สีของระบบ)
<img width="880" alt="Screen Shot 2564-08-13 at 07 15 14" src="https://user-images.githubusercontent.com/76645048/129291841-485f2897-12a9-40ea-9dd6-c70a59393efe.png">

**Comment by Americaso** [comment]
โพสต์ใน section ล่างสุด แสดงผลตัว popup เวลาชี้ที่ชื่อเพจผิด (ชี้ชื่อเพจ แต่ขึ้นชื่อ user ผู้โพสต์) 
 แก้ API **
