### ISSUE TITLE
[API] - แนะนำให้ติดตาม

### ISSUE THREAD

**Issue by chalucks** [kaogeek/spanboon#295]
-  ## เพิ่ม flag isFollow ให้ฝั่ง UI นำไปใช้งาน
![1629316533264](https://user-images.githubusercontent.com/76645048/129999670-98ff7dad-3134-4535-b946-7cf47abc3907.jpg)

**Comment by junsudas** [comment]
@Americaso ปกติมันควรจะออกแต่คนที่ยังไม่ได้ติดตามนะ check ดูหน่อยว่าส่ง userId ไปรึยัง
